sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jcbehnkedev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jcbehnkedev/docker-react npm run test -- --coverage

